# Generated by Django 4.2.6 on 2023-11-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '__first__'),
        ('users', '0002_alter_profile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carrito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.carrito'),
        ),
    ]
