# Generated by Django 4.2.6 on 2023-11-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_carrito'),
        ('users', '0003_remove_profile_email_alter_profile_avatar'),
    ]

    operations = [
    ]
