# Generated by Django 4.2.6 on 2023-11-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_casa_arrendador"),
        ("users", "0003_profile_carrito"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="alquiladas",
            field=models.ManyToManyField(blank=True, to="app.casa"),
        ),
    ]
