# Generated by Django 4.2.6 on 2023-12-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20231129_1420'),
        ('users', '0005_alquiler_alter_profile_alquiladas'),
    ]

    operations = [
    ]
