# Generated by Django 4.2.6 on 2023-12-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_casa_preciopordia'),
        ('users', '0006_merge_20231201_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='alquilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.casa'),
        ),
    ]
