# Generated by Django 4.2.6 on 2023-12-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_alquiler_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alquiler",
            name="FechaFinal",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="alquiler",
            name="FechaInicio",
            field=models.DateField(),
        ),
    ]
