# Generated by Django 4.2.6 on 2023-12-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_alquiler_fechafinal_alter_alquiler_fechainicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="alquiler",
            name="modosEntrega",
            field=models.CharField(
                choices=[
                    ("LB", "Dejar las llaves en buzon"),
                    ("LV", "Dejar las llaves con vecino"),
                    ("LP", "Entrega de llaves personal"),
                ],
                default="LP",
                max_length=2,
            ),
        ),
    ]
