# Generated by Django 4.2.6 on 2023-12-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_alquiler_fechafinal_alter_alquiler_fechainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'pendiente'), ('EN CURSO', 'en curso'), ('CANCELAD0', 'CANCELADO')], default='PENDIENTE', max_length=20),
        ),
    ]
