# Generated by Django 4.2.6 on 2023-12-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=150)),
                ('descripcion', models.TextField(max_length=500)),
                ('imagen', models.URLField()),
                ('localidad', models.TextField(max_length=50)),
                ('direccion', models.TextField(max_length=100)),
                ('precioPorDia', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500)),
                ('pretensiones', models.TextField(max_length=500)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'pendiente'), ('PROCESADA', 'procesada'), ('DESECHADA', 'desechada')], default='PENDIENTE', max_length=20)),
                ('contestacion', models.CharField(default='Sin respuesta', max_length=300)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.casa')),
            ],
        ),
    ]
