# Generated by Django 4.2.6 on 2023-11-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_rol'),
        ('app', '0002_alter_casa_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='arrendador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
