# Generated by Django 4.2.6 on 2023-11-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alquiler_alter_profile_alquiladas"),
        ("app", "0003_alter_casa_arrendador"),
    ]

    operations = [
        migrations.AddField(
            model_name="casa",
            name="ocupadas",
            field=models.ManyToManyField(blank=True, to="users.alquiler"),
        ),
        migrations.AddField(
            model_name="casa",
            name="precioPorDia",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
