# Generated by Django 4.2.6 on 2023-12-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categoria_casa_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
