# Generated by Django 4.2.6 on 2023-12-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_casa_ocupadas_casa_preciopordia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='precioPorDia',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
