# Generated by Django 4.2.6 on 2023-12-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='url',
            field=models.CharField(default=None, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
