# Generated by Django 4.2.6 on 2023-12-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comentario_reclamacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamacion',
            name='Contestación',
            field=models.CharField(default='Sin respuesta', max_length=300),
        ),
        migrations.DeleteModel(
            name='Comentario_Reclamacion',
        ),
    ]
