# Generated by Django 4.2.6 on 2023-12-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_reclamacion_contestación_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamacion',
            old_name='Contestación',
            new_name='contestacion',
        ),
    ]
