# Generated by Django 4.2.6 on 2023-12-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_alter_alquiler_user_alter_profile_user'),
        ('app', '0010_rename_contestación_reclamacion_contestacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'pendiente'), ('PROCESADA', 'procesada'), ('DESECHADA', 'desechada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
