# Generated by Django 4.2.6 on 2023-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_bool', models.BooleanField(default=False)),
                ('stripe_checkout_id', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
