# Generated by Django 4.2.6 on 2023-11-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alquiler_alter_profile_alquiladas"),
        ("shoppingCart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrito",
            name="productos",
            field=models.ManyToManyField(blank=True, to="users.alquiler"),
        ),
    ]
