# Generated by Django 4.2.6 on 2023-12-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingCart", "0003_carrito_payment_bool_carrito_stripe_checkout_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrito",
            name="payment_bool",
        ),
        migrations.RemoveField(
            model_name="carrito",
            name="stripe_checkout_id",
        ),
    ]
